.PHONY: help clean clean-logs docker-build docker-shell docker-logs docker-down

IMAGE ?= lightning-hydra-uv-docker
SHM_SIZE ?= 8g
SERVICE ?= gpu
COMPOSE ?= docker compose

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

docker-build: ## Build Docker image with Docker Compose
	IMAGE=$(IMAGE) SHM_SIZE=$(SHM_SIZE) $(COMPOSE) build

docker-shell: ## Enter Docker container
	IMAGE=$(IMAGE) SHM_SIZE=$(SHM_SIZE) $(COMPOSE) run --rm $(SERVICE) bash

docker-logs: ## Follow Docker Compose logs
	$(COMPOSE) logs -f

docker-down: ## Stop Docker Compose container and remove orphan containers
	$(COMPOSE) down --remove-orphans

# format: ## Run pre-commit hooks
# 	pre-commit run -a

# sync: ## Merge changes from main branch to your current branch
# 	git pull
# 	git pull origin main

# test: ## Run not slow tests
# 	pytest -k "not slow"

# test-full: ## Run all tests
# 	pytest

# train: ## Train the model
# 	python src/train.py
