.PHONY: help clean clean-logs docker-build docker-shell

IMAGE ?= lightning-hydra-uv-docker
SHM_SIZE ?= 8g

DOCKER_RUN = docker run --gpus all --rm -it \
						 --shm-size=$(SHM_SIZE) \
						 --ulimit memlock=-1 \
						 -v $(CURDIR)/data:/app/data \
						 -v $(CURDIR)/logs:/app/logs \
						 $(IMAGE)

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

docker-build: ## Build Docker image
	docker build -t $(IMAGE) .

docker-shell: ## Start Docker container with an interactive shell
	$(DOCKER_RUN) bash

# format: ## Run pre-commit hooks
# 	pre-commit run -a

# sync: ## Merge changes from main branch to your current branch
# 	git pull
# 	git pull origin main

# test: ## Run not slow tests
# 	pytest -k "not slow"

# test-full: ## Run all tests
# 	pytest

# train: ## Train the model
# 	python src/train.py
